/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalproject;

import javax.swing.*;
import java.util.*; 
import java.io.*;
public class RemoveAttendant extends javax.swing.JFrame {
 ArrayList<Attendant> attendants;
    public RemoveAttendant() {
        initComponents();
        attendants= new ArrayList<Attendant>();
        populateArrayList();
         }
    public void saveAttendantsToFile()
    { 
        try 
        {
        FileOutputStream file= new FileOutputStream("attendants.dat");
        ObjectOutputStream outputFile = new ObjectOutputStream(file);
        for(int i=0;i<attendants.size();i++) 
        {
            outputFile.writeObject(attendants.get(i));
        }
        outputFile.close();
        JOptionPane.showMessageDialog(null,"Successfully saved");
        this.dispose();
        }
        
       
        
        catch(IOException e) 
        { 
         JOptionPane.showMessageDialog(null, e.getMessage());   
        }
       
    }
    public void removeAttendantsToFile()
    { 
        try 
        {
        FileOutputStream file= new FileOutputStream("attendants.dat");
        ObjectOutputStream outputFile = new ObjectOutputStream(file);
        for(int i=0;i<attendants.size();i++) 
        {
            outputFile.writeObject(attendants.get(i));
        }
        outputFile.close();
        JOptionPane.showMessageDialog(null,"Successfully Removed");
        this.dispose();
        }
        
       
        
        catch(IOException e) 
        { 
         JOptionPane.showMessageDialog(null, e.getMessage());   
        }
       
    }
 public void populateArrayList() 
    {
     try 
     {
        FileInputStream file = new FileInputStream("attendants.dat"); 
        ObjectInputStream inputFile = new ObjectInputStream(file); 
        boolean endOfFile= false; 
        while(!endOfFile)
        {
         try
         { 
       
          attendants.add((Attendant)inputFile.readObject());         
        
         }
         catch(EOFException e)
        { 
            endOfFile= true;
        }
        
        
         catch(Exception f) 
         {
           JOptionPane.showMessageDialog(null, f.getMessage()); 
         }
         
        }
        inputFile.close();
     }
     catch (IOException e)
     {
         JOptionPane.showMessageDialog(null, e.getMessage());
     }
    String[] SeatLocationArray= new String[attendants.size()];
    jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(SeatLocationArray));
    for(int i=0;i<attendants.size();i++)
    {
        {
        SeatLocationArray[i]="Seat Number "+attendants.get(i).getSeatLocation()+"";
        
        }
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(SeatLocationArray));
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tan\\Desktop\\ICON PICS\\icons8-remove-user-group-man-man-32.png")); // NOI18N
        jButton1.setText("Remove Attendant");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Choose the seat location you want to remove ");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Choose Seat Location");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       int selectedIndex= jComboBox1.getSelectedIndex();
       attendants.remove(selectedIndex);
       removeAttendantsToFile();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RemoveAttendant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RemoveAttendant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RemoveAttendant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RemoveAttendant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RemoveAttendant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
